<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="insert.aspx.cs" Inherits="BankManagement.insert" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="UserStyleSheet.css" rel="stylesheet" />
    <script type="text/javascript">
	window.history.forward();
	function noBack() { window.history.forward(); }
</script>
</head>
<body onload="noBack();" 
	onpageshow="if (event.persisted) noBack();" onunload="">
    <form id="form1" runat="server">
    <div>

         <div class="header">
           <asp:Button ID="Account" runat="server" Text="Account" PostBackUrl="~/insert.aspx" CssClass="ac" />
           <asp:Button ID="UserInfo" runat="server" Text="User" PostBackUrl="~/User.aspx" CssClass="ui" />
       </div>
       
        
            <asp:TextBox ID="txtaccno" runat="server" placeholder="Account No" ></asp:TextBox>
            <asp:TextBox ID="TextBox1" runat="server" placeholder="AcType" ></asp:TextBox>
            <asp:TextBox ID="TextBox2" runat="server" placeholder="Branch" ></asp:TextBox>
            <asp:TextBox ID="TextBox3" runat="server" placeholder="AcID" ></asp:TextBox>
        
      
    
        <div>
            <div>
            <asp:Button ID="submit" Text="Submit" runat="server" OnClick="submit_Click" />
            <asp:Button ID="update" Text="Update" runat="server" OnClick="updateclick" />
            </div>

            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" OnRowDeleting="Grid1RowDeleting" AutoGenerateDeleteButton="True">

                <Columns>

                    
                   
                   <asp:TemplateField HeaderText="AccNo">
                       <ItemTemplate>
                           <asp:Label ID="AccNo" runat="server" Text='<%# Bind("AccNo")%>' />
                       </ItemTemplate>
                   </asp:TemplateField>
                    <asp:TemplateField HeaderText="Acc_Type">
                       <ItemTemplate>
                           <asp:Label ID="Acc_Type" runat="server" Text='<%# Bind("Acc_Type")%>' />
                       </ItemTemplate>
                   </asp:TemplateField>

                    <asp:TemplateField HeaderText="BranchName">
                       <ItemTemplate>
                           <asp:Label ID="BranchName" runat="server" Text='<%# Bind("BranchName")%>' />
                       </ItemTemplate>
                   </asp:TemplateField>
                    <asp:TemplateField HeaderText="AccID">
                       <ItemTemplate>
                           <asp:Label ID="AccID" runat="server" Text='<%# Bind("AccID")%>' />
                       </ItemTemplate>
                   </asp:TemplateField>

               </Columns>

               

            </asp:GridView>
            <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="AccNo" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:BoundField DataField="AccNo" HeaderText="AccNo" ReadOnly="True" SortExpression="AccNo" />
                    <asp:BoundField DataField="Acc_Type" HeaderText="Acc_Type" SortExpression="Acc_Type" />
                    <asp:BoundField DataField="BranchName" HeaderText="BranchName" SortExpression="BranchName" />
                    <asp:BoundField DataField="AccID" HeaderText="AccID" SortExpression="AccID" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:connection %>" SelectCommand="SELECT * FROM [Account]" DeleteCommand="DELETE FROM [Account] WHERE [AccNo] = @AccNo" UpdateCommand="UPDATE [Account] SET [Acc_Type] = @Acc_Type, [BranchName] = @BranchName, [AccID] = @AccID WHERE [AccNo] = @AccNo">
                <DeleteParameters>
                    <asp:Parameter Name="AccNo" Type="String" />
                </DeleteParameters>
               
                <UpdateParameters>
                    <asp:Parameter Name="Acc_Type" Type="String" />
                    <asp:Parameter Name="BranchName" Type="String" />
                    <asp:Parameter Name="AccID" Type="Int32" />
                    <asp:Parameter Name="AccNo" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <p>Delete an Item</p>
            <div>
                 <asp:TextBox ID="dltbox" runat="server" placeholder="Enter AccNo"></asp:TextBox>
                <asp:Button ID="delete" runat="server" Text="Delete" OnClick="deletion" />
                <asp:label ID="msg" runat="server"></asp:label>
            </div>
           

        </div>

       
    </div>
    </form>
</body>
</html>
